spring:
  application:
    name: MatchMaker
  datasource:
    url: jdbc:h2:mem:matchmaker
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
